Project:      output/finalproject_test1
Build Number: 0
Date:         Wed May 16 23:45:56 2012
Compiler:     ICCM8C
Version:      7.05.00


Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             lit   0150   00C5 =    197. bytes (rel,con,rom,lit)

       Addr  Global Symbol
      -----  --------------------------------
       01AF  LoadConfigTBL_finalproject_test1_Bank0
       01E6  LoadConfigTBL_finalproject_test1_Bank1
       0215  __lit_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                           idata   0215   0002 =      2. bytes (rel,con,rom,lit)

       Addr  Global Symbol
      -----  --------------------------------
       0215  __idata_start
       0217  __idata_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     psoc_config   0217   012C =    300. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0217  LoadConfigTBL_finalproject_test1_Ordered
       02DC  LoadConfigInit
       02DC  _LoadConfigInit
       02EC  LoadConfig_finalproject_test1
       02EC  _LoadConfig_finalproject_test1
       0343  __psoc_config_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     UserModules   0343   0399 =    921. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0343  _UART_TX_ISR
       0344  _UART_RX_ISR
       0394  _UART_EnableInt
       0394  UART_EnableInt
       039B  UART_DisableInt
       039B  _UART_DisableInt
       03A2  _UART_SetTxIntMode
       03A2  UART_SetTxIntMode
       03B4  _UART_Start
       03B4  UART_Start
       03BD  _UART_Stop
       03BD  UART_Stop
       03C4  UART_SendData
       03C4  _UART_SendData
       03C7  _UART_bReadTxStatus
       03C7  bUART_ReadTxStatus
       03C7  UART_bReadTxStatus
       03C7  _bUART_ReadTxStatus
       03CA  bUART_ReadRxData
       03CA  UART_bReadRxData
       03CA  _UART_bReadRxData
       03CA  _bUART_ReadRxData
       03CD  _bUART_ReadRxStatus
       03CD  bUART_ReadRxStatus
       03CD  _UART_bReadRxStatus
       03CD  UART_bReadRxStatus
       03D0  _UART_TxIntMode
       03D0  UART_TxIntMode
       03E3  _UART_IntCntl
       03E3  UART_IntCntl
       040E  UART_PutSHexByte
       040E  _UART_PutSHexByte
       0421  UART_PutSHexInt
       0421  _UART_PutSHexInt
       0428  UART_PutChar
       0428  _UART_PutChar
       0430  UART_cGetChar
       0430  _UART_cGetChar
       0438  UART_cReadChar
       0438  _UART_cReadChar
       044F  _UART_iReadChar
       044F  UART_iReadChar
       0465  _UART_PutString
       0465  UART_PutString
       046F  UART_Write
       046F  _UART_Write
       0487  UART_CWrite
       0487  _UART_CWrite
       04AF  UART_CPutString
       04AF  _UART_CPutString
       04C1  UART_PutCRLF
       04C1  _UART_PutCRLF
       04CA  UART_CmdReset
       04CA  _UART_CmdReset
       04D7  _UART_bCmdCheck
       04D7  UART_bCmdCheck
       04DC  _UART_bErrCheck
       04DC  UART_bErrCheck
       04E4  UART_bCmdLength
       04E4  _UART_bCmdLength
       04E7  UART_szGetParam
       04E7  _UART_szGetParam
       0535  UART_szGetRestOfParams
       0535  _UART_szGetRestOfParams
       053D  LCD_PrCString
       053D  _LCD_PrCString
       054F  LCD_HEX_STR
       055F  LCD_PrHexByte
       055F  _LCD_PrHexByte
       0572  LCD_PrHexInt
       0572  _LCD_PrHexInt
       0579  LCD_PrString
       0579  _LCD_PrString
       0583  _LCD_WriteData
       0583  _LCD_Write_Data
       0583  LCD_Write_Data
       0583  LCD_WriteData
       0597  _LCD_Control
       0597  LCD_Control
       063E  LCD_Init
       063E  _LCD_Init
       063E  LCD_Start
       063E  _LCD_Start
       06AA  LCD_ROW_OFFSET
       06AE  _LCD_Position
       06AE  LCD_Position
       06BA  _LCD_Delay50uTimes
       06BA  LCD_Delay50uTimes
       06C0  LCD_Delay50u_Table
       06C8  LCD_Delay50u
       06C8  _LCD_Delay50u
       06DC  __UserModules_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            text   06DC   01DC =    476. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       06DC  __text_start
       06DC  _main
       0702  _initialize
       0750  _buttonISR
       0810  _displayLCD
       089D  _echoText
       08B4  PSoC_GPIO_ISR
       08B8  __text_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            data   0000   0002 =      2. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0000  __data_start
       0000  _mode
       0002  __data_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
               virtual_registers   0002   000F =     15. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0002  __rZ
       0003  __rY
       0004  __rX
       0005  __r11
       0006  __r10
       0007  __r9
       0008  __r8
       0009  __r7
       000A  __r6
       000B  __r5
       000C  __r4
       000D  __r3
       000E  __r2
       000F  __r1
       0010  __r0
       0011  __virtual_registers_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                    InterruptRAM   0011   0005 =      5. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0011  _UART_fStatus
       0011  UART_fStatus
       0012  _UART_bRxCnt
       0012  UART_bRxCnt
       0013  NO_SHADOW
       0013  _Port_2_Data_SHADE
       0013  _NO_SHADOW
       0013  Port_2_Data_SHADE
       0014  _Port_2_DriveMode_0_SHADE
       0014  Port_2_DriveMode_0_SHADE
       0015  Port_2_DriveMode_1_SHADE
       0015  _Port_2_DriveMode_1_SHADE
       0016  __InterruptRAM_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             bss   0016   0022 =     34. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0016  _strPtr
       0016  __bss_start
       0018  _bufChar1
       0028  _bufChar
       0038  __bss_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                        UART_RAM   0038   0022 =     34. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0038  UART_aRxBuffer
       0038  _UART_aRxBuffer
       005A  __ramareas_end
       005A  __UART_RAM_end

Area                               Start  End    Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             TOP   0000   00D7 =    215. bytes (abs,ovr,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0068  __Start
       00D4  _bGetPowerSetting
       00D4  bGetPowerSetting

Files Linked      [ module(s) ]

./obj/boot.o	[ boot.asm ]
./obj/main.o	[ main.c ]
<library>	[ uartint.asm, uart.asm, psocgpioint.asm, psocconfigtbl.asm, psocconfig.asm, lcd.asm, rZ.asm, rY.asm ]
[ rX.asm, r11.asm, r10.asm, r9.asm, r8.asm, r7.asm, r6.asm, r5.asm, r4.asm, r3.asm, r2.asm, r1.asm, r0.asm ]


Area Definitions

-blit:0x150.0x3fff
-bdata:0.0xff
-rwh:SSCParmBlk:0xf7.0xff

